services:
  # === Traefik Reverse Proxy ===
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - --configFile=/traefik.yml
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - web
    labels:
      # Middleware: увеличиваем лимит тела запроса до 100 МБ
      - "traefik.http.middlewares.large-body.buffering.maxRequestBodyBytes=104857600"  # 100 МБ
      - "traefik.http.middlewares.large-body.buffering.maxResponseBodyBytes=104857600"
      - "traefik.http.middlewares.large-body.buffering.retryExpression=isNetworkError() || responseStatusCode() == 429"

  # === Backend API Service ===
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    expose:
      - "5000"
    environment:
      - APP_ENV=development
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`lonelinessgu.space`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
      # Применяем middleware для увеличения лимита загрузки
      - "traefik.http.routers.backend.middlewares=large-body"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

  # === Frontend SPA Service ===
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    expose:
      - "80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`lonelinessgu.space`, `www.lonelinessgu.space`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

# === Сети ===
networks:
  web:
    driver: bridge