entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

http:
  middlewares:
    large-body:
      buffering:
        maxRequestBodyBytes: 104857600  # 100 МБ
        maxResponseBodyBytes: 104857600
        retryExpression: isNetworkError() || responseStatusCode() == 429

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencryptresolver:
    acme:
      email: temiksp@gmail.com
      storage: /acme.json
      httpChallenge:
        entryPoint: web