# Dockerfile.backend
FROM python:3.10-slim

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем содержимое текущей директории (backend) в /app
COPY . /app

# Запуск приложения
CMD ["uvicorn", "backend.run:app", "--host", "0.0.0.0", "--port", "5000"]