entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

http:
  providers:
    docker:
      endpoint: "unix:///var/run/docker.sock"
      exposedByDefault: false

certificatesResolvers:
  letsencryptresolver:
    acme:
      email: # Write ur mail here
      storage: /acme.json
      httpChallenge:
        entryPoint: web