from tortoise import fields, models

class Company(models.Model):
    id = fields.IntField(pk=True, generated=True)
    inn = fields.CharField(max_length=40, null=True)
    name = fields.TextField(null=True)
    full_name = fields.TextField(null=True)
    status = fields.CharField(max_length=50, null=True)
    legal_address = fields.TextField(null=True)
    production_address = fields.TextField(null=True)
    additional_site_address = fields.TextField(null=True)
    main_industry = fields.CharField(max_length=255, null=True)
    sub_industry = fields.CharField(max_length=255, null=True)
    main_okved = fields.CharField(max_length=255, null=True)
    main_okved_activity = fields.TextField(null=True)
    production_okved = fields.CharField(max_length=255, null=True)
    registration_date = fields.DateField(null=True)
    director = fields.CharField(max_length=255, null=True)
    head_company = fields.CharField(max_length=255, null=True)
    head_company_inn = fields.CharField(max_length=40, null=True)
    director_contacts = fields.TextField(null=True)
    employee_contacts = fields.TextField(null=True)
    cs_responsible_contacts = fields.TextField(null=True)
    website = fields.CharField(max_length=255, null=True)
    email = fields.CharField(max_length=255, null=True)
    support_measures = fields.CharField(max_length=50, null=True)
    special_status = fields.CharField(max_length=255, null=True)
    msp_status = fields.CharField(max_length=255, null=True)
    revenue_2022 = fields.IntField(null=True)
    revenue_2023 = fields.IntField(null=True)
    revenue_2024 = fields.IntField(null=True)
    net_profit_2022 = fields.IntField(null=True)
    net_profit_2023 = fields.IntField(null=True)
    net_profit_2024 = fields.IntField(null=True)
    staff_count_total_2022 = fields.IntField(null=True)
    staff_count_total_2023 = fields.IntField(null=True)
    staff_count_total_2024 = fields.IntField(null=True)
    staff_count_moscow_2022 = fields.IntField(null=True)
    staff_count_moscow_2023 = fields.IntField(null=True)
    staff_count_moscow_2024 = fields.IntField(null=True)
    payroll_total_2022 = fields.IntField(null=True)
    payroll_total_2023 = fields.IntField(null=True)
    payroll_total_2024 = fields.IntField(null=True)
    payroll_moscow_2022 = fields.IntField(null=True)
    payroll_moscow_2023 = fields.IntField(null=True)
    payroll_moscow_2024 = fields.IntField(null=True)
    avg_salary_total_2022 = fields.FloatField(null=True)
    avg_salary_total_2023 = fields.FloatField(null=True)
    avg_salary_total_2024 = fields.FloatField(null=True)
    avg_salary_moscow_2022 = fields.FloatField(null=True)
    avg_salary_moscow_2023 = fields.FloatField(null=True)
    avg_salary_moscow_2024 = fields.FloatField(null=True)
    taxes_paid_moscow_2022 = fields.IntField(null=True)
    taxes_paid_moscow_2023 = fields.IntField(null=True)
    taxes_paid_moscow_2024 = fields.IntField(null=True)
    profit_tax_2022 = fields.IntField(null=True)
    profit_tax_2023 = fields.IntField(null=True)
    profit_tax_2024 = fields.IntField(null=True)
    property_tax_2022 = fields.IntField(null=True)
    property_tax_2023 = fields.IntField(null=True)
    property_tax_2024 = fields.IntField(null=True)
    land_tax_2022 = fields.IntField(null=True)
    land_tax_2023 = fields.IntField(null=True)
    land_tax_2024 = fields.IntField(null=True)
    ndfl_2022 = fields.IntField(null=True)
    ndfl_2023 = fields.IntField(null=True)
    ndfl_2024 = fields.IntField(null=True)
    transport_tax_2022 = fields.IntField(null=True)
    transport_tax_2023 = fields.IntField(null=True)
    transport_tax_2024 = fields.IntField(null=True)
    other_taxes_2022 = fields.IntField(null=True)
    other_taxes_2023 = fields.IntField(null=True)
    other_taxes_2024 = fields.IntField(null=True)
    excise_2022 = fields.IntField(null=True)
    excise_2023 = fields.IntField(null=True)
    excise_2024 = fields.IntField(null=True)
    investments_moscow_2022 = fields.IntField(null=True)
    investments_moscow_2023 = fields.IntField(null=True)
    investments_moscow_2024 = fields.IntField(null=True)
    export_volume_2022 = fields.IntField(null=True)
    export_volume_2023 = fields.IntField(null=True)
    export_volume_2024 = fields.IntField(null=True)
    cadastral_number_land = fields.CharField(max_length=255, null=True)
    area_land = fields.FloatField(null=True)
    permitted_use_land = fields.CharField(max_length=255, null=True)
    ownership_type_land = fields.TextField(null=True)
    land_owner = fields.TextField(null=True)
    cadastral_number_oks = fields.CharField(max_length=255, null=True)
    area_oks = fields.FloatField(null=True)
    permitted_use_oks = fields.CharField(max_length=255, null=True)
    building_type = fields.CharField(max_length=255, null=True)
    ownership_type_oks = fields.TextField(null=True)
    oks_owner = fields.TextField(null=True)
    production_area_sqm = fields.FloatField(null=True)
    standardized_product = fields.CharField(max_length=255, null=True)
    product_types = fields.TextField(null=True)
    okpd2_products = fields.TextField(null=True)
    product_segments = fields.TextField(null=True)
    product_catalog = fields.TextField(null=True)
    state_contract = fields.CharField(max_length=10, null=True)
    capacity_utilization = fields.CharField(max_length=255, null=True)
    export_supply = fields.CharField(max_length=10, null=True)
    export_volume_prev_year = fields.IntField(null=True)
    export_countries = fields.TextField(null=True)
    legal_address_coords = fields.CharField(max_length=255, null=True)
    production_address_coords = fields.CharField(max_length=255, null=True)
    additional_site_coords = fields.CharField(max_length=255, null=True)
    latitude = fields.FloatField(null=True)
    longitude = fields.FloatField(null=True)
    district = fields.CharField(max_length=255, null=True)
    area = fields.CharField(max_length=255, null=True)

    class Meta:
        table = "companies"